<?php

namespace Nilmanduil\RPGSheetBundle\Entity;

/**
 * CharacterGroupPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterGroupPersonRepository extends \Doctrine\ORM\EntityRepository
{
}
