<?php

namespace Nilmanduil\RPGSheetBundle\Entity;

/**
 * CharacterClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterClassRepository extends \Doctrine\ORM\EntityRepository
{
}
