<?php

namespace Nilmanduil\RPGSheetBundle\Entity;

/**
 * CharacterCharacteristicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterCharacteristicRepository extends \Doctrine\ORM\EntityRepository
{
}
