<?php

namespace Nilmanduil\RPGSheetBundle\Entity;

/**
 * CharacterPersonSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterPersonSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
