<?php

namespace Nilmanduil\RPGSheetBundle\Entity;

/**
 * CharacterMoneyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterMoneyRepository extends \Doctrine\ORM\EntityRepository
{
}
