<?php

namespace Nilmanduil\RPGSheetBundle\Entity;

/**
 * CharacterPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterPersonRepository extends \Doctrine\ORM\EntityRepository
{
}
