<?php

namespace Nilmanduil\RPGSheetBundle\Entity;

/**
 * CharacterGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
