<?php

namespace Nilmanduil\RPGSheetBundle\Entity;

/**
 * CharacterPersonMultiSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterPersonMultiSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
