<?php

namespace Nilmanduil\RPGSheetBundle\Entity;

/**
 * GroupMoneyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupMoneyRepository extends \Doctrine\ORM\EntityRepository
{
}
