<?php

namespace Nilmanduil\RPGSheetBundle\Entity;

/**
 * InventoryLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryLineRepository extends \Doctrine\ORM\EntityRepository
{
}
